- hosts: all
  user: coc
  become: true
  vars:
    mysql_root_password: fart
  tasks:
  - name: Install python3
    apt: 
      name: python3
      state: present
  - name: Install PyMySQL
    command: python3 -m pip install PyMySQL
  - name: Install MySQL
    apt: name=['mysql-server'] update_cache=yes cache_valid_time=3600 state=present
    with_items:
    - mysql-server
  - name: Enable external access
    replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '(bind-address.*)'
      replace: '#\1'
  - name: Start the MySQL service
    service: 
      name: mysql 
      state: started
      enabled: true
  - name: update mysql root password for all root accounts
    mysql_user: 
      name: root 
      host: "%" 
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - 127.0.0.1
      - localhost
  - name: Create a new database with name 'quotes'
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: quotes
      state: present
