- hosts: all
  user: coc
  become: true
  vars:
    mysql_root_password: fart
  tasks:

  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
    - mysql-server
    - python3
    - python3-pip

  - name: Install PyMySQL
    command: python3 -m pip install PyMySQL
    
  - name: Update firewall rules
    command: ufw allow 3306/tcp
    
  - name: Enable external access
    replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '(bind-address.*)'
      replace: '#\1'
      
  - name: Start the MySQL service
    service: 
      name: mysql 
      state: started
      enabled: true
      
#  - name: update mysql root password for all root accounts
#    mysql_user: 
#      name: root 
#      login_user: root
#      login_unix_socket: /var/run/mysqld/mysqld.sock
#      host: "localhost" 
#      password: "{{ mysql_root_password }}"
#      priv: "*.*:ALL,GRANT"
#    become: yes

  - name: Create a new database with name 'quotes'
    mysql_db:
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: quotes
      state: present
      
  - name: Create DBuser
    mysql_user:
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: bob
      password: "12345"
      priv: 'quotes.*:ALL,GRANT/*.*:PROCESS'
      state: present

