- hosts: all
  user: coc
  become: true
  vars:
    mysql_root_password: fart
  tasks:
  
#  - name: Install python3
#    apt: 
#      name: python3
#      state: present
#  - name: Install pip
#    apt: 
#      name: python3-pip
#      state: present  

  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
    - mysql-server
    - python3
    - python3-pip

  - name: Install PyMySQL
    command: python3 -m pip install PyMySQL
    

  - name: Enable external access
    replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '(bind-address.*)'
      replace: '#\1'
      
  - name: Start the MySQL service
    service: 
      name: mysql 
      state: started
      enabled: true
      
      
  - name: Create DBuser
    mysql_user:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: bob
      password: "12345"
      priv: '*.*:ALL'
      state: present

#  - name: update mysql root password for all root accounts
#    mysql_user: 
#      become: true
#      host: "{{ item }}"
#      name: root 
#      password: "{{ mysql_root_password }}"
#      login_user: root
#      login_password: "{{ mysql_root_password }}"
#      check_implicit_admin: yes
#      priv: "*.*:ALL,GRANT"
#      with_items:
#      - "{{ ansible_hostname }}"
#      - 127.0.0.1
#      - localhost
      
  - name: Create a new database with name 'quotes'
    mysql_db:
      login_user: root
#      login_password: "{{ mysql_root_password }}"
      name: quotes
      state: present
