- hosts: all
  user: coc
  become: true
  vars:
    mysql_root_password: fart
  tasks:
  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
    - mysql-server
  - name: Start the MySQL service
    service: 
      name: mysql 
      state: started
      enabled: true
  - name: update mysql root password for all root accounts
    mysql_user: 
      name: root 
      host: "%" 
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - 127.0.0.1
      - localhost
  - name: Create a new database with name 'quotes'
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: quotes
      state: present
