- name: MariaDB
  hosts: all
  gather_facts: true
  become: true

  tasks:
  
  - name: Install dependencies (collections)
    run: ansible-galaxy collection install -r collections/requirements.yml -p collections
  
  - name: Create a new database with name 'bobdata'
    community.mysql.mysql_db:
      name: bobdata
      state: present

