- hosts: all
  user: coc
  become: true
  vars:
    mysql_root_password: fart  # change later to use variable passed into playbook
  tasks:

  - name: Install MySQL
    apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
    with_items:
    - mysql-server
    - python3
    - python3-pip

  - name: Install PyMySQL
    command: python3 -m pip install PyMySQL
    
  - name: Update firewall rules
    command: ufw allow 3306/tcp
    
  - name: Enable external access
    replace:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: '(bind-address.*)'
      replace: '#\1'
      
  - name: Start the MySQL service
    service: 
      name: mysql 
      state: started
      enabled: true

  - name: Create a new database with name 'qod'
    mysql_db:
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: qod
      state: present

  - name: ls current directory
    shell: pwd
    register: shell_result

  - name: out
    debug:
      var: shell_result

  - name: Copy DB SQL files
    copy:
      src: "{{ item }}"
      dest: '/tmp/qod/'
      force: yes
      owner: mysql
    with_items:
    - 1_createdb.sql
    - 2_authors.sql
    - 3_genres.sql
    - 4_quotes.sql
      
  - name: Create DBuser
    mysql_user:
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: bob
      password: "12345"
      priv: 'qod.*:ALL/*.*:PROCESS'
      host: '%'
      state: present
      
  - name: restart mysql
    service:
      name: mysql
      state: restarted

  - name: import SQL
    mysql_db:
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      state: import
      name: all
      encoding: latin1
      target: "{{ item }}"
    with_items:
    - /tmp/qod/1_createdb.sql
    - /tmp/qod/2_authors.sql
    - /tmp/qod/3_genres.sql
    - /tmp/qod/4_quotes_sm.sql