---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: qod-application
  namespace: qod-project
  generation: 2
  labels:
    app: qod
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      app: qod