---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: qod-web-channel-deployment
  namespace: qod-channel-namespace
  labels:
    app: qod
    tier: web
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: qod-web-channel-deployment
      labels:
        app: qod
        tier: web
    spec:
        selector:
          matchLabels:
            app: qod
            tier: web
        template:
          metadata:
            labels:
              app: qod
              tier: web
          spec:
            containers:
            - name: qod-web
              image: docker.io/ibmicpcoc/qod-web:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 3001
              env:
              - name: QOD_API_URL
                value: "http://qod-api-service:3000"
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: qod-web-channel-service
  namespace: qod-channel-namespace
  labels:
    app: qod
    tier: web
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: qod-web-service
      labels:
        app: qod
        tier: web
    spec:
      type: ClusterIP
      ports:
        - targetPort: 3001
          port: 3001
          protocol: TCP
          name: http
      selector:
          app: qod
          tier: web
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: qod-web-channel-route
  namespace: qod-channel-namespace
  labels:
    app: qod
    tier: web
spec:
  template:
    kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: qod-web-route
      labels:
        app: qod
        tier: web
    spec:
      subdomain: ''
      to:
        kind: Service
        name: qod-web-service
        weight: 100
      port:
        targetPort: http
      wildcardPolicy: None